# Generated by Django 5.2.5 on 2025-10-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=250),
            preserve_default=False,
        ),
    ]
